server:
  port: 9000

#logging:
#  level:
#    org.springframework.web: DEBUG

spring:
  application:
    name: auth-jwt-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8314/eureka/
